[project]
name = "mistral-ocr-milvus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "mistralai>=1.5.1",
    "pymilvus>=2.5.5",
    "ruff>=0.9.10",
    "sentence-transformers>=3.4.1",
    "uvicorn>=0.34.0",
]